services:
  db:
    image: postgres:16
    container_name: devdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ViZgie2d3WDasgN
      POSTGRES_DB: chatati
    ports:
      - "5432:5432"
    volumes:
      - C:/Users/michi/Projects/Database/pgChatati:/var/lib/postgresql/data
